{{+
  exports.defaultHeaders = {
    'Host': 'localhost:4000',
    'Content-Type': 'application/json'
  };
}}
###
POST /api/user/login
...defaultHeaders
{
  "email": "abc@test.com",
  "password": "password"
}

HTTP/1.1 401  - Unauthorized
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 49
etag: W/"31-MK/uwNXUQ/EVloyJoXs8tTrZAjs"
date: Sat, 27 Dec 2025 00:23:14 GMT
connection: close
###
POST /api/user/register
...defaultHeaders
{
    "name": "Test User",
    "password": "test1234",
    "email": "test1234@example.org"
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 175
etag: W/"af-ssH4cjQheCuX6D2Ger0As2P8d/4"
date: Sat, 27 Dec 2025 00:34:00 GMT
connection: close